version: '3'

services:
  description:
    container_name: item-description-container
    build: ./
    depends_on:
      - 'database'
    ports:
      - '80:3003'

  database:
    container_name: mongo-container
    image: mongo:latest
    ports:
      - '27017:27017'